name: Automation test for Nix

on:
  pull_request:
    types: [opened, synchronize, closed]
    branches: '*'

jobs:
  flake-check:
    name: Flake Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v13

      - name: Enable Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v7

      - name: Check flake
        run: nix flake check --all-systems


  build-macos:
    name: Build on macOS
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v13

      - name: Enable Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v7

      - name: Build Home Manager configuration
        run: nix build .#homeConfigurations.tttol.activationPackage

